common:
  app_name: 'ms_template'
  api_key: ''
  is_debug: false
  use_new_relic: false
  use_datadog: false
  use_senstry: false
  use_sentry_dsn: false
  is_maintenance: false
  timezone: 'UTC+7'
  lang: 'en-US'
  environment: 'development'
db:
  maria:
    master_db:
      name: 'db_golang'
      user: 'root'
      host: '172.17.0.2'
      port: 3306
      pass: 'root'
    slave_db:
      name: 'db_golang'
      user: 'root'
      host: '172.17.0.2'
      port: 3306
      pass: 'root'
  redis_cluster:
    host: '10.0.0.2:7000'
    retry_count: 100
    retry_duration: 1
    max_active: 50
    max_idle: 50
    idle_timeout: 240
    dial_connection_timeout: 10