// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	UserList
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserGender int32

const (
	UserGender_UNDEFINED UserGender = 0
	UserGender_MALE      UserGender = 1
	UserGender_FEMALE    UserGender = 2
)

var UserGender_name = map[int32]string{
	0: "UNDEFINED",
	1: "MALE",
	2: "FEMALE",
}
var UserGender_value = map[string]int32{
	"UNDEFINED": 0,
	"MALE":      1,
	"FEMALE":    2,
}

func (x UserGender) String() string {
	return proto.EnumName(UserGender_name, int32(x))
}
func (UserGender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type User struct {
	Id       string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Password string     `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Gender   UserGender `protobuf:"varint,4,opt,name=gender,enum=UserProtocol.UserGender" json:"gender,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetGender() UserGender {
	if m != nil {
		return m.Gender
	}
	return UserGender_UNDEFINED
}

type UserList struct {
	List []*User `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserList) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "UserProtocol.User")
	proto.RegisterType((*UserList)(nil), "UserProtocol.UserList")
	proto.RegisterEnum("UserProtocol.UserGender", UserGender_name, UserGender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/UserProtocol.Users/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	Register(context.Context, *User) (*google_protobuf.Empty, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserProtocol.Users/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Register(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserProtocol.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Users_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xd7, 0x2c, 0xdf, 0xd2, 0xbd, 0x5f, 0x1d, 0xe3, 0x3d, 0x48, 0xa8, 0x97, 0xd2, 0x83,
	0x14, 0x0f, 0x99, 0xd6, 0x8b, 0xd7, 0xc9, 0x32, 0x11, 0xe6, 0x90, 0xc2, 0x2e, 0xde, 0x56, 0x1b,
	0x4b, 0xa0, 0x5b, 0x4a, 0x92, 0xa1, 0xfe, 0xf7, 0x92, 0xcc, 0x5f, 0xa0, 0xb7, 0xe7, 0xfd, 0x3c,
	0xcf, 0x9b, 0xbc, 0x3c, 0x00, 0x7b, 0x2b, 0x0d, 0xef, 0x8d, 0x76, 0x1a, 0x8f, 0xd6, 0x56, 0x9a,
	0x07, 0x2f, 0x9f, 0x74, 0x97, 0x9e, 0xb6, 0x5a, 0xb7, 0x9d, 0x9c, 0x06, 0xaf, 0xde, 0x3f, 0x4f,
	0xe5, 0xb6, 0x77, 0x6f, 0x87, 0x68, 0xfe, 0x0a, 0xd4, 0x87, 0x71, 0x0c, 0x44, 0x35, 0x2c, 0xca,
	0xa2, 0x62, 0x54, 0x11, 0xd5, 0x20, 0x02, 0xdd, 0x6d, 0xb6, 0x92, 0x91, 0x40, 0x82, 0xc6, 0x14,
	0x92, 0x7e, 0x63, 0xed, 0x8b, 0x36, 0x0d, 0x1b, 0x06, 0xfe, 0x35, 0xe3, 0x05, 0xc4, 0xad, 0xdc,
	0x35, 0xd2, 0x30, 0x9a, 0x45, 0xc5, 0xb8, 0x64, 0xfc, 0xe7, 0x0d, 0x61, 0xb8, 0x0d, 0x7e, 0xf5,
	0x91, 0xcb, 0x4b, 0x48, 0x3c, 0x5d, 0x2a, 0xeb, 0xf0, 0x0c, 0x68, 0xa7, 0xac, 0x63, 0x51, 0x36,
	0x2c, 0xfe, 0x97, 0xf8, 0x7b, 0xb7, 0x0a, 0xfe, 0xf9, 0x25, 0xc0, 0xf7, 0x4b, 0x78, 0x0c, 0xa3,
	0xf5, 0x6a, 0x2e, 0x16, 0x77, 0x2b, 0x31, 0x9f, 0x0c, 0x30, 0x01, 0x7a, 0x3f, 0x5b, 0x8a, 0x49,
	0x84, 0x00, 0xf1, 0x42, 0x04, 0x4d, 0xca, 0x19, 0xfc, 0xf3, 0x2b, 0x16, 0xaf, 0x21, 0xa9, 0x64,
	0xab, 0xac, 0x93, 0x06, 0xff, 0xf8, 0x21, 0x3d, 0xe1, 0x87, 0x9e, 0xf8, 0x67, 0x4f, 0x5c, 0xf8,
	0x9e, 0xf2, 0xc1, 0x0d, 0x7d, 0x24, 0x7d, 0x5d, 0xc7, 0x81, 0x5f, 0xbd, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x43, 0xeb, 0xa1, 0x14, 0x69, 0x01, 0x00, 0x00,
}
